apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlops-major-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mlops-major
  template:
    metadata:
      labels:
        app: mlops-major
    spec:
      containers:
      - name: mlops-major-container
        image: harshitagupta217/mlops_major:latest
        ports:
        - containerPort: 5000
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
